add_newline = false

[line_break]
disabled = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
vimcmd_symbol = "[V](bold green)"
vimcmd_replace_one_symbol = "[V](bold purple)"
vimcmd_replace_symbol = "[V](bold purple)"
vimcmd_visual_symbol = "[V](bold yellow)"

[sudo]
style = "bold blue"
